const CONFIG = {
    introTitle: 'Quyên ơii',
    introDesc: `Bé ấn vào nút dưới i`,
    btnIntro: 'hihi',
    title: 'chọn iii',
    desc: 'Qui iu em gất nhìuuuu ',
    btnYes: 'cx iu tqui nhìu',
    btnNo: 'Hong iu qui',
    question:'Saoo em lại yeuuu chongg',
    btnReply: 'Gửi cho anh ',
    reply: 'Yêu vo nhattttt',
    mess: 'iu em nhìuuu',
    messDesc: 'Chiều anh mang trà sữa với quà qua cho em nhó',
    btnAccept: 'daaaa',
} 
