const CONFIG = {
    introTitle: 'Cậu ơi',
    introDesc: `Ấn vào nút phía dưới đi :3`,
    btnIntro: 'hihi',
    title: 'Chọn đi :>',
    desc: 'design by Huy ',
    btnYes: 'Vẫn cứ là thích anh í',
    btnNo: 'Không, Anh trai à ',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu cậu nhất :3',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Tối nay ship cho ly trà sữa nhó :3.',
    btnAccept: 'Okiiiii lunnn',
} 
