const CONFIG = {
    introTitle: 'Bạn nhỏ ơii',
    introDesc: `Bấm vào nút phía dưới i`,
    btnIntro: 'Này nè',
    title: 'chọn iii',
    desc: '',
    btnYes: 'iu',
    btnNo: 'm cuts',
    question:'Saoo lai iu??????????/,
    btnReply: 'Gửi cho tqui',
    reply: 'Iu cậu',
    mess: 'Tớ cx iu cậu,
    messDesc: 'Chiều tớ mang trà sữa cho nhennn',
    btnAccept: 'ukiiiiii',
} 
